config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: "users/sessions", registrations: "users/registrations" }

  root 'purple/dashboard#home'
  get 'interactions' => 'purple/dashboard#interactions'
  get 'discover' => 'purple/dashboard#discover'
  get 'messages' => 'purple/dashboard#messages'
  get 'search(/:keyword)' => 'purple/dashboard#search', as: :search

  resources :stories, :module => "purple", :path => "s", except: [:new] do 
    collection do
      get 'new(/:parent)', :action => :new, :as => 'new'
    end
    member do
      post 'repost'
      post 'favorite'
    end
  end

  get 'discover' => 'purple/profiles#discover'
  resources :profiles, :module => "purple", :path => "u", param: :username, except: [:index, :create, :new, :destroy] do
    member do
      post 'follow'
      get 'followers(/:page)', :action => :followers, :as => 'followers'
      get 'following(/:page)', :action => :following, :as => 'following'
      get 'favorites(/:page)', :action => :favorites, :as => 'favorites'
      get 'recomendation(/:page)', :action => :recomendation, :as => 'recomendation'
    end
  end

end

app/controllers/purple/dashboard_controller.rb
## TODO
# Story
# - Interaction (Repost, Favorite)
# - Ajax (Feed, Interaction)
# Keyword
# - Fix Search
# User
# - Recomendation
# Misc
# - Notifiaction
###

class Purple::DashboardController < ApplicationController
	before_action :authenticate_user!

	def home
		@user = current_user
		@stories = Story.find_by_sql(["SELECT * FROM stories WHERE user_id IN (SELECT follow_id FROM relations WHERE user_id = ?) OR user_id = ? ORDER BY created_at DESC;", current_user.id, current_user.id]);
		@trends = Keyword.find_by_sql(["SELECT value, count(*) as rep FROM keywords WHERE created_at > ? GROUP BY value ORDER BY rep DESC LIMIT 10;", Date.today-1]);
	end

	def interactions
		@user = current_user
		@trends = Keyword.find_by_sql(["SELECT value, count(*) as rep FROM keywords WHERE created_at > ? GROUP BY value ORDER BY rep DESC LIMIT 10;", Date.today-1]);
		@stories = Story.find_by_sql(["SELECT * FROM stories WHERE id in (SELECT story_id FROM keywords WHERE value = ?) ORDER BY created_at DESC;", "@" + current_user.username]);		
	end

	def discover
	end

	def messages
	end

	def search
		## Without join, not strict
		@stories = Story.find_by_sql(["SELECT * FROM stories WHERE id in (SELECT DISTINCT story_id FROM keywords WHERE value in (?)) ORDER BY created_at DESC;", params[:keyword].split]);
		@trends = Keyword.find_by_sql(["SELECT value, count(*) as rep FROM keywords WHERE created_at > ? GROUP BY value ORDER BY rep DESC LIMIT 10;", Date.today-1]);

		#@join = ""
		#params[:keyword].split.each do |p|
		#	@join = "#{@join} INNER JOIN (SELECT story_id FROM keywords WHERE value = #{p}) #{p} ON ("
		#end
		## With join, strict
		#@stories = Story.find_by_sql(["SELECT * FROM stories WHERE id in (SELECT story_id FROM keywords ?) ORDER BY created_at DESC;", @join]);
	end
end

app/controllers/purple/profiles_controller.rb
###
### TODO :
### - ajax pagination for profile listing
### - Handle image size
###

class Purple::ProfilesController < ApplicationController
	## Get 'discover'
	# show all user ordered by follower count
	def discover
		@users = User.order(followers_count: :desc).limit(10)
	end

	## Get 'recomendation'
	# based on mutual relation
	def recomendation
		render html: '<b>Coming soon<b/>'.html_safe
	end

	## Get 'show'
	def show
		@user = User.find_by username: params[:username] #.select("cover", "avatar", "fullname", "username", "description", "location", "website", "follower_count", "following_count")
		@relation = Relation.find_by user: current_user, follow: @user
		@stories = Story.where('user_id' => @user.id).order(created_at: :desc)

		respond_to do |format|
			format.html
		end
	end

	## Get 'edit'
	def edit
		if !user_signed_in?
			redirect_to new_user_session_path
		elsif current_user.username != params[:username]
			redirect_to profile_path(params[:username])
		end
		@user = User.find_by username: params[:username]
	end

	## Patch 'update'
	def update
		@user = User.find_by username: params[:username]

		if edit_profile_params
			params[:user][:avatar] = upload_image(profile_params, "avatar") if params[:user][:avatar]
			params[:user][:cover] = upload_image(profile_params, "cover") if params[:user][:cover]

			@user.update(edit_profile_params)
			redirect_to profile_path(params[:username])
		else
			render 'edit'
		end
	end

	## Get 'followers'
	def followers
		offset = 10 * params[:page].to_i
		@user = User.find_by username: params[:username]
		@users = User.joins('LEFT OUTER JOIN relations ON relations.user_id = users.id').where('relations.follow_id' => @user).select("username", "fullname", "avatar", "cover", "description", "location", "followers_count", "following_count").limit(10).offset(offset)
		@relation = Relation.find_by user: current_user, follow: @user

		respond_to do |format|
			format.html
			format.js { render :file => "users/profile/profile_list.js.erb" }
		end
	end

	## Get 'following'
	def following
		offset = 10 * params[:page].to_i
		@user = User.find_by username: params[:username]
		@users = User.joins('LEFT OUTER JOIN relations ON relations.follow_id = users.id').where('relations.user_id' => @user).select("username", "fullname", "avatar", "cover", "description", "location", "followers_count", "following_count").limit(10).offset(offset)
		@relation = Relation.find_by user: current_user, follow: @user

		respond_to do |format|
			format.html
			format.js { render :file => "users/profile/profile_list.js.erb" }
		end
	end

	## Get 'favorites'
	def favorites
		@user = User.find_by username: params[:username] #.select("cover", "avatar", "fullname", "username", "description", "location", "website", "follower_count", "following_count")
		@relation = Relation.find_by user: current_user, follow: @user
		@stories = Story.where('user_id' => @user.id)

		respond_to do |format|
			format.html
		end
	end

	## Post 'follow'
	def follow
		# Check wether user is exist
		user_to_follow = User.find_by username: params[:username]
		# make sure it's validated and not the current_user profile
		if (user_to_follow and current_user) and (user_to_follow.username != current_user.username)
			# Check wether record exist before create or destroying the relation 
			relation = Relation.find_by user: current_user, follow: user_to_follow
			if (relation)
				if (relation.destroy)
#					current_user.following_count -= 1
#					user_to_follow.follower_count -= 1
#					current_user.save
#					user_to_follow.save
				end
			else
				if (Relation.create user: current_user, follow: user_to_follow)
#					current_user.following_count += 1
#					user_to_follow.follower_count += 1
#					current_user.save
#					user_to_follow.save
				end
			end
		end
		redirect_to profile_path(params[:username])
	end

	private
		## Helper to upload image, image will be replaced if user already upload the same type
		## return the image link
		def upload_image(params, directory)
		  	file_name = params["#{directory}"].original_filename
		   	file_type = file_name.split('.').last
		  
		  	# Create file path
		  	path = File.join("public/" + directory, "#{@user.id}." + file_type)

		  	# Write the file
		  	File.open(path, "wb") { |f| f.write(params["#{directory}"].read) }
		  	return File.join(directory, "#{@user.id}." + file_type)
		end

		## params for edit profile form
		def edit_profile_params
			params.require(:user).permit(:fullname, :description, :location, :website, :avatar, :cover, :theme)
		end
end

app/controllers/purple/stories_controller.rb
## TODO
# Story
# - Reply

class Purple::StoriesController < ApplicationController
	def index
	end

	def create
		if !user_signed_in?
			redirect_to new_user_session_path
		end


#		params[:story][:attachement] = upload_image(new_story_params, "upload") if params[:story][:attachement]
		
#		p new_story_params
		@story = Story.new(new_story_params)
		@story.user = current_user

		if @story.save
			map_keywords(@story.content)
			
			redirect_to(:back)
		else
			render 'new'
		end
	end

	def new
		if !user_signed_in?
			redirect_to new_user_session_path
		end

		@story = Story.new
	end

	def edit
		@story = Story.find_by id: params[:id]
		if !user_signed_in?
			redirect_to new_user_session_path
		elsif current_user != @story.user
			redirect_to story_path(params[:id])
		end
	end

	def show
		@story = Story.find_by id: params[:id]
	end

	def update
		@story = Story.find_by id: params[:id]
		if !user_signed_in?
			redirect_to new_user_session_path
		elsif current_user != @story.user
			redirect_to story_path(params[:id])
		end

		if (@story.update(update_story_params))
			Keyword.delete_all("story_id = #{@story.id}")
			map_keywords(@story.content)

			redirect_to story_path(@story)
		else
			render 'edit'
		end
	end

	def destroy
		@story = Story.find_by id: params[:id]

		if !user_signed_in?
			redirect_to new_user_session_path
		elsif current_user != @story.user
			redirect_to story_path(params[:id])
		end

		@story.destroy
		redirect_to stories_path
	end

	def repost
		if !user_signed_in?
			redirect_to new_user_session_path
		end

		@story = Story.find_by id: params[:id]
		interaction = Interaction.find_or_initialize_by(user: current_user, owner: @story.user, story: @story)
		interaction.user = current_user
		interaction.owner = @story.user
		interaction.story = @story
		interaction.repost = !interaction.repost

		if (interaction.repost)
			@story.repost_count = @story.repost_count + 1 
		else
			@story.repost_count = @story.repost_count - 1
		end

		interaction.save
		@story.save

		redirect_to(:back)
	end

	def favorite
		if !user_signed_in?
			redirect_to new_user_session_path
		end

		@story = Story.find_by id: params[:id]
		interaction = Interaction.find_or_initialize_by(user: current_user, owner: @story.user, story: @story)
		interaction.user = current_user
		interaction.owner = @story.user
		interaction.story = @story
		interaction.favorite = !interaction.favorite

		if (interaction.favorite)
			@story.favorite_count = @story.favorite_count + 1 
		else
			@story.favorite_count = @story.favorite_count - 1
		end

		interaction.save
		@story.save
			
		redirect_to(:back)
	end

	private
		def new_story_params
			params.require(:story).permit(:content, :attachement, :location, :parent)
		end

		def update_story_params
			params.require(:story).permit(:content, :attachement)
		end

		def map_keywords(story)
			keywords = Hash.new(0)
			@story.content.gsub(/[^0-9A-Za-z # @]/, ' ').split.each do |k| 
				keywords[k] += 1
			end

			records = []
			keywords.each_pair do |k,v|
				records.push(Keyword.new(:story => @story, :value => k, :weight => v))
			end
			Keyword.import records
		end

		## Helper to upload image, image will be replaced if user already upload the same type
		## return the image link
		def upload_image(params, directory)
		  	file_name = params[:attachement].original_filename
		   	file_type = file_name.split('.').last
		  
		  	# Create file path
		  	path = File.join("public/" + directory, "#{Time.now.to_i}." + file_type)

		  	# Write the file
		  	File.open(path, "wb") { |f| f.write(params[:attachement].read) }
		  	return File.join(directory, "#{Time.now.to_i}." + file_type)
		end
end

app/helpers/purple/dashboard_helper.rb
module Purple::DashboardHelper
end

app/helpers/purple/profiles_helper.rb
module Purple::ProfilesHelper
end

app/helpers/purple/stories_helper.rb
module Purple::StoriesHelper
end

app/views/purple/profiles/_profile_card_about.html.erb
<%
	valid_uri = @user.website
	if (valid_uri and valid_uri[0..6] != "http://" and valid_uri[0..7] != "https://")
		valid_uri = "http://" + valid_uri
	end
%>
<div class="ui card">
	<div class="image">
  		<img src="/<%= @user.avatar %>">
	</div>
	<div class="content">
  		<div class="header"><%= @user.fullname %></div>
  		<div class="meta">
	  		<%= link_to "@#{@user.username}", profile_path(@user.username) %>
  		</div>
  		<div class="description">
  			<p><%= @user.description %></p>
  		</div>
	</div>
	<div class="extra content">
		<%= raw("<i class='marker icon'></i> #{@user.location} <br>") if @user.location %>
		<%= raw("<i class='external link square icon'></i> <a href='#{valid_uri}' target='_blank'>#{@user.website}</a><br>") if @user.website %>
		<i class="wait icon"></i> Joined since <%= @user.created_at.strftime("%B %Y") %>
	</div>
	</div>

app/views/purple/profiles/_profile_card_collections.html.erb
<div class="ui special five cards">
<% @users.each do |u| %>
	<div class="card">
		<div class="dimmable image">
	    	<div class="ui inverted dimmer">
	        	<div class="content">
	          		<div class="center">
	            		<div class="ui purple button">Follow</div>
	          		</div>
	        	</div>
	      	</div>
	      	<img src="/<%= u.avatar %>">
		</div>
		<div class="content">
	  		<div class="header"><%= u.fullname %></div>
	  		<div class="meta">
	    		<%= link_to "@#{u.username}", profile_path(u.username) %>
	  		</div>
		</div>
	</div>
<% end %>
</div>

app/views/purple/profiles/_profile_card_statistics.html.erb
<div class="ui card">
	<div class="image">
  		<img src="/<%= @user.avatar %>">
	</div>
	<div class="content">
  		<div class="header"><%= @user.fullname %></div>
  		<div class="meta">
	  		<%= link_to "@#{@user.username}", profile_path(@user.username) %>
  		</div>
	</div>
	<div class="extra content">
    	<div class="ui mini statistics">
			<a class="statistic" href="<%= profile_path(@user.username) %>">
				<div class="label" style="font-size:12px">Posts</div>
			    <div class="value">22</div>
			</a>
			<a class="statistic" href="<%= following_profile_path(@user.username) %>">
				<div class="label" style="font-size:12px">Following</h1></div>
				<div class="value"><%= @user.following_count %></div>
			</a>
			<a class="statistic" href="<%= followers_profile_path(@user.username) %>">
				<div class="label" style="font-size:12px">Followers</div>
				<div class="value"><%= @user.followers_count %></div>
			</a>
		</div>
	</div>
</div>

app/views/purple/profiles/_profile_header.html.erb
<div class="ui purple pointing menu">
  <img class="ui rounded image" src="/<%= @user.cover %>" width="900" height="225">
  <a class="<%= "active" if current_page?(controller: 'purple/profiles', action: 'show') %> item" href="<%= profile_path(@user.username) %>">
    <i class="comment icon"></i> Posts
    <div class="ui small teal label">133</div>
  </a>
  <a class="<%= "active" if current_page?(controller: 'purple/profiles', action: 'following') %> item" href="<%= following_profile_path(@user.username) %>">
    <i class="user icon" ></i> Following
    <div class="ui small teal label"><%= @user.following_count %></div>
  </a>
  <a class="<%= "active" if current_page?(controller: 'purple/profiles', action: 'followers') %> item" href="<%= followers_profile_path(@user.username) %>">
    <i class="user icon"></i> Followers
    <div class="ui small teal label"><%= @user.followers_count %></div>
  </a>
  <a class="<%= "active" if current_page?(controller: 'purple/profiles', action: 'favorites') %> item" href="<%= favorites_profile_path(@user.username) %>">
    <i class="star icon"></i> Favorites
    <div class="ui small teal label">133</div>
  </a>
  <div class="right menu">
    <% if user_signed_in? %>
      <% if current_user.username != @user.username %>
        <%=	link_to raw("<div class='ui labeled button'>#{(@relation ? 'Unfollow' : 'Follow')}</div>'"), follow_profile_path(@user.username), class: "item", :method => :post %>
      <% else %>
        <%= link_to raw("<div class='ui labeled button'>Edit</div>'"), edit_profile_path(@user.username), class: "item" %>
      <% end %>
    <% end %>
  </div>
</div>

app/views/purple/profiles/_profiles_listing.html.erb
<% @users.each do |u| %>
	<%= u.username %> | <%= u.description %> | <%= u.location %> | followers : <%= u.followers_count %> | follwing : <%= u.following_count %> | <%= link_to 'view', profile_path(u.username) %><br />
<% end %>

app/views/purple/profiles/discover.html.erb
<%= render 'profiles_listing' %>

app/views/purple/profiles/edit.html.erb
<h1>Update profile</h1>

<%= form_for :user, url: :profile, method: :patch do |f| %>
	<div class="field">
	    <%= f.label :fullname %><br />
	    <%= f.text_field :fullname, autofocus: true %>
	</div>

	<div class="field">
	    <%= f.label :description %><br />
	    <%= f.text_area :description %>
	</div>

	<div class="field">
	    <%= f.label :location %><br />
	    <%= f.text_field :location %>
	</div>

	<div class="field">
	    <%= f.label :website %><br />
	    <%= f.text_field :website %>
	</div>

	<div class="field">
	    <%= f.label :avatar %><br />
	    <%= f.file_field :avatar %>
	</div>

	<div class="field">
	    <%= f.label :cover %><br />
	    <%= f.file_field :cover %>
	</div>

	<div class="field">
	    <%= f.label :theme %><br />
	    <%= f.text_field :theme %>
	</div>

	<div class="actions">
		<%= f.submit "Update" %>
	</div>
<% end %>

app/views/purple/profiles/favorites.html.erb
<% if @user == nil %>
	<p>
		User not found
	</p>
<% else %>
	<div class="four wide column">
	  	<%= render 'purple/profiles/profile_card_about' %>
  		<%= render 'purple/dashboard/about_widget' %>
	</div>
	<div class="twelve wide column">
		<%= render 'purple/profiles/profile_header' %>
		<%= render 'purple/stories/stories_listing' %>
	</div>	
<% end %>

app/views/purple/profiles/followers.html.erb
<% if @user == nil %>
	<p>
		User not found
	</p>
<% else %>
	<div class="four wide column">
	  	<%= render 'purple/profiles/profile_card_about' %>
  		<%= render 'purple/dashboard/about_widget' %>
	</div>
	<div class="twelve wide column">
		<%= render 'purple/profiles/profile_header' %>
		<%= render 'purple/profiles/profile_card_collections' %>
	</div>
<% end %>

app/views/purple/profiles/following.html.erb
<% if @user == nil %>
	<p>
		User not found
	</p>
<% else %>
	<div class="four wide column">
	  	<%= render 'purple/profiles/profile_card_about' %>
  		<%= render 'purple/dashboard/about_widget' %>
	</div>
	<div class="twelve wide column">
		<%= render 'purple/profiles/profile_header' %>
		<%= render 'purple/profiles/profile_card_collections' %>
	</div>
<% end %>

app/views/purple/profiles/profile_list.js.erb
<% @relation.each do |r| %>
	$('more').replaceWith('<%= r.username %> | <%= r.description %> | <%= r.location %> | followers : <%= r.followers_count %> | follwing : <%= r.following_count %> | <%= link_to 'view', profile_path(r.username) %><br />');
<% end %>

app/views/purple/profiles/show.html.erb
<% if @user == nil %>
	<p>
		User not found
	</p>
<% else %>
	<div class="four wide column">
	  	<%= render 'purple/profiles/profile_card_about' %>
  		<%= render 'purple/dashboard/about_widget' %>
	</div>
	<div class="twelve wide column">
		<%= render 'purple/profiles/profile_header' %>
		<%= render 'purple/stories/stories_listing' %>
	</div>
<% end %>